server:
  port: 0

spring:
  application:
    name: sender-ms
  mail:
    host: smtp.gmail.com
    port: 587
    username: kafkanotifyApp@gmail.com
    password: kafkanotifyApp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

